### PR TITLE
Transition Type Changes

### LINKED ISSUE #28: Conditional Transition editor not working
Changing the `transition` on a conditional transition option causes that transition option to be set to empty and then not changeable again.  
examplitis_1

examplitis_2

examplitis_3

### PR DESCRIPTION
**Pull request by schreiaj**
- Transition Type changing
- Creation and Deletion of new Transitions where applicable 
- Creation and Deletion of new Code elements in all Codes displays
- Fixes #28 
- Changes `EDIT_NODE` to delete the attribute when `value` is not defined 
- Enables deletion of States

### CODE REVIEW

File: src/components/editor/Code.js [hunk 1]
```diff
@@ -40,8 +43,13 @@ export class Codes extends Component<CodesProps> {
     return (
       <div>
         {this.props.codes.map((code, i) => {
-          return <Code key={i} onChange={this.props.onChange(i)} code={code} />
+          return <div>
```
Comment (arscan) [inline src/components/editor/Code.js]: When I run `yarn test`, a warning is raised here because there is no key on this element.

**Comment by kjmahalingam** [comment]
This PR seems to add all functionality described. I think that the text for adding and removing transitions was initially unclear, since I couldn't initially tell which transition each 'remove' button referred to. But that said, we have a ways to go as far as making the text of the editors look cleaner in other ways, anyway. I'm fine with merging this in and having an editor text overhaul later on, but holding off until we address @arscan's comment above.

**Comment by arscan** [comment]
Looks good.  Agree that this needs styling soon, but we can do that in a later PR.  Also, at some point we should put in tests that test all these interactions, because there is no way that we can do that manually.
